// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/historico/(pages)/historico_page.dart' as a0;
import 'app/home/(pages)/home_page.dart' as a1;
import 'app/login/(pages)/login_page.dart' as a2;
import 'app/not_found_page.dart' as a3;
import 'app/testes/(pages)/testes_page.dart' as a4;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/historico',
        uri: Uri.parse('/historico'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.HistoricoPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.LoginPage(),
        ),
      ),
      RouteEntity(
        key: '/not_found',
        uri: Uri.parse('/not_found'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.NotFoundPage(),
        ),
      ),
      RouteEntity(
        key: '/testes',
        uri: Uri.parse('/testes'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.TestesPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  historico: '/historico',
  home: '/home',
  login: '/login',
  notFound: '/not_found',
  testes: '/testes',
);
