// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/historico/(pages)/[idApplication]_page.dart' as a2;
import 'app/home/(pages)/home_page.dart' as a3;
import 'app/login/(pages)/login_page.dart' as a1;
import 'app/not_found_page.dart' as a0;
import 'app/testes/(pages)/[idHistorico]_page.dart' as a4;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/not_found',
        uri: Uri.parse('/not_found'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.NotFoundPage(),
        ),
      ),
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.LoginPage(),
        ),
      ),
      RouteEntity(
        key: '/historico/[idApplication]',
        uri: Uri.parse('/historico/[idApplication]'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.HistoricoPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/testes/[idHistorico]',
        uri: Uri.parse('/testes/[idHistorico]'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.TestesPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  notFound: '/not_found',
  login: '/login',
  historico: (
    path: '/historico',
    $idApplication: '/historico/[idApplication]',
  ),
  home: '/home',
  testes: (
    path: '/testes',
    $idHistorico: '/testes/[idHistorico]',
  ),
);
