name: back_end
description: A sample command-line application.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  mocktail: ^1.0.0
  flutterando_analysis: ^0.0.2

dependencies:
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.6
  get_it: ^7.6.0
  mysql_client: ^0.0.27
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_multipart: ^1.0.0
  shelf_hotreload: ^1.4.0
  s3_storage: ^1.0.4
  tmp_path: ^1.2.2
  shelf_static: ^1.1.3
  shelf_swagger_ui: ^1.0.0+2
  shelf_cors_headers: ^0.1.5
  dhttpd: ^4.0.1
  open_url: ^2.0.1
  crypto: ^3.0.3
  uno: ^1.1.9
  intl: ^0.18.1
